---
- hosts: lathe

  vars:
    - packages:
      - tmux
      - vim
      - ack-grep
      - jq
      - httpie
      - stow
    - personalrepositories:
      - dotfiles
      - thugletics
    - gae_language: go
    - elao_motd: "A lathe is the only tool that can replicate itself."

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
           cache_valid_time=3600
      become: yes

  roles:
    - oh-my-zsh
    - role: motd
      become: yes

  tasks:
    - name: install packages
      apt: name="{{ item }}"
           state=present
      become: yes
      with_items: packages

    - name: ensure github.com is a known host
      lineinfile: dest=~/.ssh/known_hosts
                  create=yes
                  state=present
                  line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
                  regexp="^github\\.com"

    - name: clone personal git repositories
      git: repo="github.com:mamachanko/{{ item }}.git"
           dest="~/{{ item }}"
           force=yes
           accept_hostkey=yes
      with_items: personalrepositories

    - name: delete existing .zshrc
      file: name=~/.zshrc
            state=absent

    - name: install dotfiles
      command: stow . chdir=~/dotfiles

    - name: download PIP installer
      get_url: url=https://bootstrap.pypa.io/get-pip.py
               dest=/tmp/get-pip.py

    - name: install PIP
      become: yes
      command: python /tmp/get-pip.py

    - name: install virtualenv & wrapper
      become: yes
      pip: name="{{ item }}"
           state=present
      with_items:
        - virtualenv
        - virtualenvwrapper

    - name: enable bash history complete for arrow keys
      lineinfile: dest=~/.inputrc
                  line="{{ item }}"
                  state=present
                  create=yes
      with_items:
        - '"\e[A":history-search-backward'
        - '"\e[B":history-search-forward'

    - name: download Go App SDK
      get_url: url=https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.34.zip
               dest=/tmp/go_appengine.zip

    - name: unzip Go App Engine SDK
      unarchive: src=/tmp/go_appengine.zip
                 dest=~/
                 creates=~/go_appengine
                 copy=no

    - name: download Google Cloud SDK
      get_url: url="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-102.0.0-linux-x86_64.tar.gz"
               dest="/tmp/google-cloud-sdk.tar.gz"
               force=no
               checksum="sha1:5c6cb7db4257c9597636f540d9f923f001aab959"

    - name: unarchive Google Cloud SDK
      unarchive: src="/tmp/google-cloud-sdk.tar.gz"
                 dest="~/"
                 copy=no
                 creates="~/google-cloud-sdk/"

    - name: install Google Cloud SDK
      lineinfile: dest="~/.zshenv"
                  line="source ~/google-cloud-sdk/path.zsh.inc"

    - name: download Google App Engine Go SDK
      get_url: url="https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.34.zip"
               dest="/tmp/go_appengine.zip"
               force=no
               checksum="sha1:98ea8ff4c429c2ee288473ffe564c5eaee5ae6d1"

    - name: unarchive Google App Engine Go SDK
      unarchive: src="/tmp/go_appengine.zip"
                 dest="~/"
                 copy=no
                 creates="~/go_appengine/"

    - name: install Google App Engine Go SDK
      lineinfile: dest="~/.zshenv"
                  line="export PATH=$PATH:~/go_appengine"
